// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations must use DIRECT_URL (port 5432, direct connection).
    // Supabase's pooler (port 6543, pgBouncer transaction mode) doesn't support
    // the DDL commands Prisma needs for schema migrations.
    url: process.env["DIRECT_URL"],
  },
});
