/**
 * prisma/seed.ts
 *
 * Seeds the database with:
 *   1. Yarns from data/yarn-library-carpets-bazaar.csv
 *   2. Designs (run process-designs.ts first to upload images and get URLs)
 *
 * Usage:
 *   npx prisma db seed
 */

import "dotenv/config";
import fs from "fs";
import path from "path";
import { parse } from "csv-parse/sync";
import { PrismaClient } from "@/app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const db = new PrismaClient({ adapter });

// ─── Yarn seeding ──────────────────────────────────────────────────────────────

type YarnCsvRow = {
  code: string;
  name: string;
  hex: string;
  material: string;
  pile_type: string;
  sort_order: string;
};

async function seedYarns(): Promise<void> {
  const csvPath = path.join(process.cwd(), "data", "yarn-library-carpets-bazaar.csv");

  if (!fs.existsSync(csvPath)) {
    console.warn("Yarn CSV not found at data/yarn-library-carpets-bazaar.csv — skipping.");
    return;
  }

  const raw = fs.readFileSync(csvPath, "utf-8");
  const rows: YarnCsvRow[] = parse(raw, {
    columns: true,
    skip_empty_lines: true,
    trim: true,
  });

  console.log(`Seeding ${rows.length} yarns...`);

  for (const row of rows) {
    await db.yarn.upsert({
      where: { code: row.code },
      update: {
        name: row.name,
        hex: row.hex.startsWith("#") ? row.hex : `#${row.hex}`,
        material: row.material || null,
        pileType: row.pile_type || null,
        sortOrder: row.sort_order ? parseInt(row.sort_order, 10) : 0,
      },
      create: {
        code: row.code,
        name: row.name,
        hex: row.hex.startsWith("#") ? row.hex : `#${row.hex}`,
        material: row.material || null,
        pileType: row.pile_type || null,
        sortOrder: row.sort_order ? parseInt(row.sort_order, 10) : 0,
      },
    });
  }

  console.log(`✓ Yarns seeded.`);
}

// ─── Design seeding ────────────────────────────────────────────────────────────
//
// Designs are seeded from a JSON manifest generated by scripts/process-designs.ts.
// If the manifest doesn't exist yet, designs are skipped with a reminder.

type DesignManifestEntry = {
  slug: string;
  name: string;
  width: number;
  height: number;
  imageUrl: string;
  sourceBmpUrl: string;
  palette: Array<{
    index: number;
    hex: string;
    pixelCount: number;
    percentage: number;
  }>;
};

async function seedDesigns(): Promise<void> {
  const manifestPath = path.join(
    process.cwd(),
    "data",
    "designs",
    "manifest.json"
  );

  if (!fs.existsSync(manifestPath)) {
    console.warn(
      "data/designs/manifest.json not found.\n" +
        "Run `npx tsx scripts/process-designs.ts` first to generate it."
    );
    return;
  }

  const designs: DesignManifestEntry[] = JSON.parse(
    fs.readFileSync(manifestPath, "utf-8")
  );

  console.log(`Seeding ${designs.length} designs...`);

  for (const design of designs) {
    await db.design.upsert({
      where: { slug: design.slug },
      update: {
        name: design.name,
        imageUrl: design.imageUrl,
        sourceBmpUrl: design.sourceBmpUrl,
        width: design.width,
        height: design.height,
        palette: design.palette,
      },
      create: {
        name: design.name,
        slug: design.slug,
        imageUrl: design.imageUrl,
        sourceBmpUrl: design.sourceBmpUrl,
        width: design.width,
        height: design.height,
        palette: design.palette,
      },
    });
    console.log(`  ✓ ${design.name}`);
  }

  console.log(`✓ Designs seeded.`);
}

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  await seedYarns();
  await seedDesigns();
}

main()
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
