/**
 * prisma/seed.ts
 *
 * Seeds the database with designs from data/designs/manifest.json.
 * Run process-designs.ts first to generate the manifest.
 *
 * Yarns are managed separately via `npm run import-yarns`
 * (scripts/import-yarn-libraries.ts) and are never touched here.
 *
 * Usage:
 *   npx prisma db seed
 */

import "dotenv/config";
import fs from "fs";
import path from "path";
import { PrismaClient } from "@/app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const db = new PrismaClient({ adapter });

// ─── Design seeding ────────────────────────────────────────────────────────────
//
// Designs are seeded from a JSON manifest generated by scripts/process-designs.ts.
// If the manifest doesn't exist yet, designs are skipped with a reminder.

type DesignManifestEntry = {
  slug: string;
  name: string;
  width: number;
  height: number;
  imageUrl: string;
  sourceBmpUrl: string;
  palette: Array<{
    index: number;
    hex: string;
    pixelCount: number;
    percentage: number;
    matchedYarnCode?: string;
  }>;
};

async function seedDesigns(): Promise<void> {
  const manifestPath = path.join(
    process.cwd(),
    "data",
    "designs",
    "manifest.json"
  );

  if (!fs.existsSync(manifestPath)) {
    console.warn(
      "data/designs/manifest.json not found.\n" +
        "Run `npx tsx scripts/process-designs.ts` first to generate it."
    );
    return;
  }

  const designs: DesignManifestEntry[] = JSON.parse(
    fs.readFileSync(manifestPath, "utf-8")
  );

  console.log(`Seeding ${designs.length} designs...`);

  for (const design of designs) {
    await db.design.upsert({
      where: { slug: design.slug },
      update: {
        name: design.name,
        imageUrl: design.imageUrl,
        sourceBmpUrl: design.sourceBmpUrl,
        width: design.width,
        height: design.height,
        palette: design.palette,
      },
      create: {
        name: design.name,
        slug: design.slug,
        imageUrl: design.imageUrl,
        sourceBmpUrl: design.sourceBmpUrl,
        width: design.width,
        height: design.height,
        palette: design.palette,
      },
    });
    console.log(`  ✓ ${design.name}`);
  }

  console.log(`✓ Designs seeded.`);
}

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  await seedDesigns();
}

main()
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
